version: "3.7"

services:
  app:
    image: subs-api
    ports:
      - "8206:8206"
    working_dir: /app

  mysql:
    image: mysql:5.7
    volumes:
      - api-mysql-data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes

volumes:
  api-mysql-data:
