version: '2'

vars:
  VERSION: {sh: git tag -l --sort=-v:refname | head -n 1}
  BUILD_TIME: {sh: date +%FT%T%z}
  COMMIT: {sh: git log --max-count=1 --pretty=format:%aI_%h}
  LDFLAGS: -ldflags "-w -s -X main.version=$(version) -X main.build=$(build_time) -X main.commit=$(commit)"
  APP_NAME: subs-api-v6
  SRC_DIR: .
  BUILD_DIR: build

tasks:
  build:
    desc: Build the go binary for current platform.
    cmds:
      - go build -o {{.BUILD_DIR}}/{{.APP_NAME}}{{exeExt}} {{.LDFLAGS}} -tags production  -v {{.SRC_DIR}}

  run:
    desc: Run the program
    cmds:
      - ./{{.BUILD_DIR}}/{{.APP_NAME}}{{exeExt}} -production=false -livemode=false

  now:
    desc: Show current time.
    cmds:
      - echo {{now | date "2006-01-02T15:04:05Z07:00"}}
      - echo {sh: date +%FT%T%z}
