#!/usr/bing/env groovy

pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                echo 'Build sandbox version'
                sh 'make build APP=sandbox'
                archiveArtifacts artifacts: 'build/*', fingerprint: true
            }
        }
        stage('Deploy') {
            when {
                expression {
                    currentBuild.result == null || currentBuild.result == 'SUCCESS'
                }
            }
            steps {
                echo 'Sync config file'
                sh 'make config'
                echo 'Copy binary'
                sh 'make publish APP=sandbox'
                sh 'make restart APP=sandbox'
            }
        }
    }
}
