#!/usr/bing/env groovy

pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                sh 'make install-go'
                echo 'Build sandbox version'
                sh 'make build ENV=sandbox'
                archiveArtifacts artifacts: 'build/*', fingerprint: true
            }
        }
        stage('Deploy') {
            when {
                expression {
                    currentBuild.result == null || currentBuild.result == 'SUCCESS'
                }
            }
            steps {
                echo 'Sync config file'
                sh 'make config'
                echo 'Copy binary'
                sh 'make publish ENV=sandbox'
                sh 'make restart ENV=sandbox'
            }
        }
    }
}
