#!/usr/bing/env groovy

pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                echo 'Build sandbox version'
                sh 'cd cmd/subs_sandbox && make build'
                sh 'make downconfig'
                archiveArtifacts artifacts: 'build/linux/*', fingerprint: true
            }
        }
        stage('Deploy') {
            when {
                expression {
                    currentBuild.result == null || currentBuild.result == 'SUCCESS'
                }
            }
            steps {
                echo 'Sync config file'
                sh 'make upconfig'
                echo 'Copy binary'
                sh 'cd cmd/subs_sandbox && make publish'
                sh 'cd cmd/subs_sandbox && make restart'
            }
        }
    }
}
