package faker

const StripeInvoice = `
{
    "id": "in_1HvzCfBzTK0hABgJklW9Azi5",
    "object": "invoice",
    "account_country": "GB",
    "account_name": "THE FINANCIAL TIMES LIMITED",
    "account_tax_ids": null,
    "amount_due": 3000,
    "amount_paid": 3000,
    "amount_remaining": 0,
    "application_fee_amount": null,
    "attempt_count": 1,
    "attempted": true,
    "auto_advance": false,
    "billing_reason": "subscription_create",
    "charge": "ch_1HvzCgBzTK0hABgJIYA2l5T0",
    "collection_method": "charge_automatically",
    "created": 1607407057,
    "currency": "gbp",
    "custom_fields": null,
    "customer": "cus_FRgIy7R6sn5nI7",
    "customer_address": null,
    "customer_email": "neefrankie@163.com",
    "customer_name": null,
    "customer_phone": null,
    "customer_shipping": null,
    "customer_tax_exempt": "none",
    "customer_tax_ids": [],
    "default_payment_method": null,
    "default_source": null,
    "default_tax_rates": [],
    "description": null,
    "discount": null,
    "discounts": [],
    "due_date": null,
    "ending_balance": 0,
    "footer": null,
    "hosted_invoice_url": "https://invoice.stripe.com/i/acct_1EpW3EBzTK0hABgJ/invst_IX3JDL71myt78H3vInXJuI6OuKcf1hU",
    "invoice_pdf": "https://pay.stripe.com/invoice/acct_1EpW3EBzTK0hABgJ/invst_IX3JDL71myt78H3vInXJuI6OuKcf1hU/pdf",
    "last_finalization_error": null,
    "lines": {
        "object": "list",
        "data": [
            {
                "id": "il_1HvzCfBzTK0hABgJJKQZaEtb",
                "object": "line_item",
                "amount": 3000,
                "currency": "gbp",
                "description": "1 × Standard (at £30.00 / year)",
                "discount_amounts": [],
                "discountable": true,
                "discounts": [],
                "livemode": false,
                "metadata": {},
                "period": {
                    "end": 1638943057,
                    "start": 1607407057
                },
                "plan": {
                    "id": "plan_FOdfeaqzczp6Ag",
                    "object": "plan",
                    "active": true,
                    "aggregate_usage": null,
                    "amount": 3000,
                    "amount_decimal": "3000",
                    "billing_scheme": "per_unit",
                    "created": 1562567504,
                    "currency": "gbp",
                    "interval": "year",
                    "interval_count": 1,
                    "livemode": false,
                    "metadata": {
                        "tier": "standard",
                        "cycle": "year"
                    },
                    "nickname": "Standard Yearly Price",
                    "price": "prod_FOde1wE4ZTRMcD",
                    "tiers_mode": null,
                    "transform_usage": null,
                    "trial_period_days": null,
                    "usage_type": "licensed"
                },
                "price": {
                    "id": "plan_FOdfeaqzczp6Ag",
                    "object": "price",
                    "active": true,
                    "billing_scheme": "per_unit",
                    "created": 1562567504,
                    "currency": "gbp",
                    "livemode": false,
                    "lookup_key": null,
                    "metadata": {
                        "tier": "standard",
                        "cycle": "year"
                    },
                    "nickname": "Standard Yearly Price",
                    "price": "prod_FOde1wE4ZTRMcD",
                    "recurring": {
                        "aggregate_usage": null,
                        "interval": "year",
                        "interval_count": 1,
                        "trial_period_days": null,
                        "usage_type": "licensed"
                    },
                    "tiers_mode": null,
                    "transform_quantity": null,
                    "type": "recurring",
                    "unit_amount": 3000,
                    "unit_amount_decimal": "3000"
                },
                "proration": false,
                "quantity": 1,
                "subscription": "sub_IX3JAkik1JKDzW",
                "subscription_item": "si_IX3JJ7rrB8wmwY",
                "tax_amounts": [],
                "tax_rates": [],
                "type": "subscription"
            }
        ],
        "has_more": false,
        "total_count": 1,
        "url": "/v1/invoices/in_1HvzCfBzTK0hABgJklW9Azi5/lines"
    },
    "livemode": false,
    "metadata": {},
    "next_payment_attempt": null,
    "number": "57EC0A25-0001",
    "paid": true,
    "payment_intent": "pi_1HvzCfBzTK0hABgJl13bQZda",
    "period_end": 1607407057,
    "period_start": 1607407057,
    "post_payment_credit_notes_amount": 0,
    "pre_payment_credit_notes_amount": 0,
    "receipt_number": null,
    "starting_balance": 0,
    "statement_descriptor": null,
    "status": "paid",
    "status_transitions": {
        "finalized_at": 1607407057,
        "marked_uncollectible_at": null,
        "paid_at": 1607407057,
        "voided_at": null
    },
    "subscription": "sub_IX3JAkik1JKDzW",
    "subtotal": 3000,
    "tax": null,
    "total": 3000,
    "total_discount_amounts": [],
    "total_tax_amounts": [],
    "transfer_data": null,
    "webhooks_delivered_at": 1607407063
}`
